name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: List STuff
      run: ls
    - name: Restore dependencies
      run: ./SuperMarket.API/dotnet restore
    - name: Build
      run: ./SuperMarket.API/dotnet build --no-restore
    - name: Test
      run: ./SuperMarket.API.Test/dotnet test --no-build --verbosity normal
