name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: List STuff
      run: ls
    - name: dotnet help
      run: dotnet -h
    - name: Restore dependencies
      run: dotnet restore ./SuperMarket.API
    - name: Build
      run: dotnet build --no-restore ./SuperMarket.API
    - name: Test
      run: dotnet test --no-build --verbosity normal ./SuperMarket.API.Test
